# permissions for end users to edit mdevs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mdev-editor-role
rules:
- apiGroups:
  - mdev.my.domain
  resources:
  - mdevs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mdev.my.domain
  resources:
  - mdevs/status
  verbs:
  - get
